# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.example.com:
    environment:
      - ORDERER_GENERAL_TLS_ENABLED=false

  peer0.org1.example.com:
    environment:
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - 7052:7052
    command: peer node start --peer-chaincodedev=true

  peer1.org1.example.com:
    environment:
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - 8052:7052
    command: peer node start --peer-chaincodedev=true

  peer0.org2.example.com:
    environment:
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - 17052:7052
    command: peer node start --peer-chaincodedev=true

  peer1.org2.example.com:
    environment:
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - 18052:7052
    command: peer node start --peer-chaincodedev=true
